#!/usr/bin/env bash
# Linux / WSL2 development workstation optimizer
# Works on native Ubuntu/Debian as well as WSL2.
# Run with: bash optimize-linux.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP_DIR="$HOME/.dev-optimizer-backups/$(date +%Y%m%d_%H%M%S)"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

section() { echo -e "\n${BLUE}=== $1 ===${NC}"; }
ok() { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }

is_wsl() {
    [[ -f /proc/version ]] && grep -qi microsoft /proc/version
}

backup_file() {
    local file="$1"
    if [ -f "$file" ]; then
        mkdir -p "$BACKUP_DIR"
        cp "$file" "$BACKUP_DIR/"
        ok "Backed up $file"
    fi
}

require_command() {
    if ! command -v "$1" &>/dev/null; then
        warn "$1 not found, skipping related steps"
        return 1
    fi
    return 0
}

# --- Backup existing configs ---
section "Backing up existing configurations"
mkdir -p "$BACKUP_DIR"
backup_file "$HOME/.wslconfig"
backup_file "$HOME/.vscode-server/data/Machine/settings.json"
backup_file "$HOME/.ssh/config"
backup_file "$HOME/.bashrc"
backup_file "$HOME/.zshrc.local"
backup_file "$HOME/.gitconfig"
backup_file "$HOME/.npmrc"
backup_file "$HOME/.config/pnpm/rc"

# --- .wslconfig (WSL only) ---
if is_wsl; then
    section "Configuring WSL2 (.wslconfig)"
    WSL_USER="${USER:-$(whoami)}"
    WSL_CONFIG_HOST_PATH="/mnt/c/Users/${WSL_USER}/.wslconfig"
    if [ -d "/mnt/c/Users/${WSL_USER}" ]; then
        total_mem_gb=$(awk '/MemTotal/{print int($2/1024/1024)}' /proc/meminfo)
        wsl_mem=$((total_mem_gb - 12))
        [ "$wsl_mem" -lt 8 ] && wsl_mem=8
        [ "$wsl_mem" -gt "$total_mem_gb" ] && wsl_mem=$((total_mem_gb - 4))
        cpu_count=$(nproc)

        mkdir -p /mnt/c/wsl-swap 2>/dev/null || true
        cat > "$WSL_CONFIG_HOST_PATH" <<EOF
[wsl2]
# Auto-generated by dev-workstation-optimizer
# Host has ${total_mem_gb} GB RAM; allocates ${wsl_mem} GB to WSL
memory=${wsl_mem}GB
processors=${cpu_count}
swap=4GB
swapFile=C:\\\\wsl-swap\\\\wslswap.vhdx
localhostForwarding=true
dnsTunneling=true
autoMemoryReclaim=gradual
pageReporting=true
networkingMode=mirrored
EOF
        ok "Created $WSL_CONFIG_HOST_PATH with memory=${wsl_mem}GB, processors=${cpu_count}"
        warn "Restart WSL with: wsl --shutdown && wsl"
    else
        warn "/mnt/c/Users/$WSL_USER not found; .wslconfig not created"
    fi
else
    section "Skipping .wslconfig (native Linux detected)"
    ok "Running native Linux optimizations"
fi

# --- zram and kernel tuning ---
section "Installing zram and tuning kernel parameters"
if command -v apt-get &>/dev/null; then
    if ! command -v zramswap &>/dev/null; then
        sudo apt-get update
        sudo apt-get install -y zram-tools
    fi

    sudo sed -i 's/^#*ALGO=.*/ALGO=lzo-rle/' /etc/default/zramswap 2>/dev/null || true
    sudo sed -i 's/^#*PERCENT=.*/PERCENT=25/' /etc/default/zramswap 2>/dev/null || true
    sudo sed -i 's/^#*PRIORITY=.*/PRIORITY=100/' /etc/default/zramswap 2>/dev/null || true
    grep -q '^ALGO=' /etc/default/zramswap || echo 'ALGO=lzo-rle' | sudo tee -a /etc/default/zramswap
    grep -q '^PERCENT=' /etc/default/zramswap || echo 'PERCENT=25' | sudo tee -a /etc/default/zramswap
    grep -q '^PRIORITY=' /etc/default/zramswap || echo 'PRIORITY=100' | sudo tee -a /etc/default/zramswap

    cat <<'SYSCONF' | sudo tee /etc/sysctl.d/99-wsl-dev.conf
# Dev workstation optimizations
vm.swappiness=10
vm.vfs_cache_pressure=50
vm.oom_kill_allocating_task=1
vm.dirty_ratio=15
vm.dirty_background_ratio=5
SYSCONF

    sudo sysctl --system
    sudo systemctl enable zramswap
    sudo systemctl restart zramswap
    ok "zram configured and started"
else
    warn "apt-get not found; zram setup skipped"
fi

# --- Disable unnecessary services ---
section "Disabling unnecessary services"
for svc in apparmor snapd landscape-client apport; do
    if systemctl is-enabled "$svc" &>/dev/null || systemctl is-active "$svc" &>/dev/null; then
        sudo systemctl disable --now "$svc" || true
        ok "Disabled $svc"
    fi
done

# --- VS Code Server settings ---
section "Configuring VS Code Server settings"
VSCODE_SETTINGS_DIR="$HOME/.vscode-server/data/Machine"
mkdir -p "$VSCODE_SETTINGS_DIR"
cat > "$VSCODE_SETTINGS_DIR/settings.json" <<'EOF'
{
  "typescript.tsserver.maxTsServerMemory": 3072,
  "typescript.tsserver.nodePath": "node",
  "search.followSymlinks": false,
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/node_modules/**": true,
    "**/.next/**": true,
    "**/dist/**": true,
    "**/.turbo/**": true,
    "**/coverage/**": true,
    "**/build/**": true
  },
  "files.exclude": {
    "**/.git": true,
    "**/.DS_Store": true,
    "**/node_modules": true,
    "**/.next": true,
    "**/dist": true,
    "**/.turbo": true,
    "**/coverage": true
  },
  "telemetry.telemetryLevel": "off"
}
EOF
ok "VS Code Server settings written"

# --- Git performance ---
section "Tuning Git performance"
git config --global core.fsmonitor true
git config --global core.untrackedCache true
git config --global feature.manyFiles true
git config --global pack.threads "$(nproc)"
git config --global core.deltaBaseCacheLimit 2g
git config --global core.packedGitWindowSize 128m
git config --global core.packedGitLimit 512m
ok "Git performance settings applied"

# --- SSH multiplexing ---
section "Configuring SSH multiplexing"
mkdir -p "$HOME/.ssh/controlmasters"
chmod 700 "$HOME/.ssh/controlmasters"

if [ -f "$HOME/.ssh/config" ]; then
    if ! grep -q "ControlMaster auto" "$HOME/.ssh/config"; then
        cat >> "$HOME/.ssh/config" <<'EOF'

Host *
  ControlMaster auto
  ControlPath ~/.ssh/controlmasters/%r@%h:%p
  ControlPersist 5m
  ServerAliveInterval 60
  ServerAliveCountMax 3
EOF
        ok "Added default SSH multiplexing to existing config"
    else
        ok "SSH multiplexing already configured"
    fi
else
    cat > "$HOME/.ssh/config" <<'EOF'
Host *
  ControlMaster auto
  ControlPath ~/.ssh/controlmasters/%r@%h:%p
  ControlPersist 5m
  ServerAliveInterval 60
  ServerAliveCountMax 3
EOF
    chmod 600 "$HOME/.ssh/config"
    ok "Created SSH config with multiplexing"
fi

# --- npm / pnpm ---
section "Tuning npm and pnpm concurrency"
if command -v npm &>/dev/null; then
    npm config set maxsockets 20
    npm config set fetch-retries 3
    npm config set fetch-retry-mintimeout 20000
    npm config set fetch-retry-maxtimeout 120000
    ok "npm concurrency tuned"
fi

if command -v pnpm &>/dev/null; then
    pnpm config set fetch-retries 3
    pnpm config set network-concurrency 16
    ok "pnpm concurrency tuned"
fi

# --- Shell environment ---
section "Adding shell environment variables"
SHELL_LOCAL="$HOME/.zshrc.local"
cat > "$SHELL_LOCAL" <<'EOF'
# Dev workstation optimizer overrides
export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1
export BUILDKIT_PROGRESS=plain
export MAKEFLAGS="-j$(nproc)"
export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)
export GOMAXPROCS=$(nproc)
export npm_config_cache="$HOME/.npm"
export PNPM_HOME="$HOME/.local/share/pnpm"
EOF
ok "Wrote $SHELL_LOCAL"

if [ -f "$HOME/.bashrc" ]; then
    if ! grep -q "DOCKER_BUILDKIT=1" "$HOME/.bashrc"; then
        cat >> "$HOME/.bashrc" <<'EOF'

# Dev workstation optimizer overrides
export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1
export MAKEFLAGS="-j$(nproc)"
export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)
export GOMAXPROCS=$(nproc)
export npm_config_cache="$HOME/.npm"
export PNPM_HOME="$HOME/.local/share/pnpm"
EOF
        ok "Updated .bashrc"
    fi
fi

# --- Docker daemon config ---
section "Enabling Docker BuildKit"
if command -v docker &>/dev/null; then
    if [ ! -f /etc/docker/daemon.json ]; then
        cat <<'DOCKERCONF' | sudo tee /etc/docker/daemon.json
{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "features": {
    "buildkit": true
  },
  "experimental": false,
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
  }
}
DOCKERCONF
        sudo systemctl restart docker || true
        ok "Docker BuildKit enabled"
    else
        warn "/etc/docker/daemon.json already exists; not modified"
    fi
fi

# --- Cleanup script ---
section "Installing weekly cleanup script"
cp "$SCRIPT_DIR/cleanup.sh" "$HOME/.local/bin/dev-cleanup"
chmod +x "$HOME/.local/bin/dev-cleanup"
ok "Installed ~/.local/bin/dev-cleanup"

section "Optimization Complete"
echo -e "${GREEN}Backups saved to:${NC} $BACKUP_DIR"
echo -e "${YELLOW}Next steps:${NC}"
if is_wsl; then
    echo "  1. Run 'wsl --shutdown' from Windows, then reopen WSL"
fi
echo "  2. Run 'free -h' and 'swapon --show' to verify"
echo "  3. Run '~/.local/bin/dev-cleanup' weekly"
if is_wsl; then
    echo "  4. Run the Windows PowerShell optimizer from the windows/ folder"
fi
